network:
  ethernets:
    ens33:
      dhcp4: false
      dhcp6: false
      addresses: [192.168.232.1/24]
      routes:
        - to: default 
          via: 192.168.233.2
      nameservers:
        addresses: [192.168.232.1, 8.8.8.8, 8.8.4.4]
  version: 2
